version: '3.8'
services:
  odoo: 
    image: odoo:16.0
    env_file: priv.env
    depends_on:
      - psql
    ports:
      - "8069:8069"
    volumes:
      - data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./custom-addons:/mnt/extra-addons
  psql:
    image: postgres:15.6-alpine3.19
    env_file: priv.env
    volumes:
      - db:/var/lib/pgsql/data/pgdata

volumes:
  data:
  db:
